# Imports

In [1]:
import numpy as np
import pandas as pd
import copy

In [2]:
aa_df = pd.read_hdf('/home/kevin/git/xplor_functions/xplor/data/all_frames_sPRE_sim.h5')

In [22]:
cluster_ids = {}
cluster_ids_aa = {}
cluster_ids_cg = {}

In [25]:
for (ubq_site, count_id_from_df), rows in aa_df.groupby([('data', '', 'ubq_site'), ('data', '', 'count_id')]):   
    if ubq_site not in cluster_ids:
        cluster_ids[ubq_site] = np.concatenate([np.load(f'/mnt/data/kevin/xplor_analysis_files/cluster_membership_aa_{ubq_site}.npy'), np.load(f'/mnt/data/kevin/xplor_analysis_files/cluster_membership_cg_{ubq_site}.npy')])
        cluster_ids_aa[ubq_site] = np.load(f'/mnt/data/kevin/xplor_analysis_files/cluster_membership_aa_{ubq_site}.npy')
        cluster_ids_cg[ubq_site] = np.load(f'/mnt/data/kevin/xplor_analysis_files/cluster_membership_cg_{ubq_site}.npy')
        
    if count_id_from_df == -1:
        print()
        prev = np.inf
        
    hdbscan_id_from_df = rows[('data', '', 'cluster_id')].unique()
    assert len(hdbscan_id_from_df) == 1
    hdbscan_id_from_df = hdbscan_id_from_df[0]
    unique, unique_counts = np.unique(cluster_ids[ubq_site], return_counts=True)
#     print(unique)
#     print(unique_counts)
    
    index_in_unique = np.where(unique == hdbscan_id_from_df)[0]
    counts = unique_counts[index_in_unique][0]
    assert counts < prev
    prev = counts
    print(f"ubq_site: {ubq_site:>3}, hdbscan_id: {hdbscan_id_from_df:>2}, count_id: {count_id_from_df:>2}, count_total: {counts:>6}, counts_aa: {np.count_nonzero(cluster_ids_aa[ubq_site] == hdbscan_id_from_df):>6}, counts_cg: {np.count_nonzero(cluster_ids_cg[ubq_site] == hdbscan_id_from_df):>6}")


ubq_site: k29, hdbscan_id: -1, count_id: -1, count_total: 572515, counts_aa:  84785, counts_cg: 487730
ubq_site: k29, hdbscan_id:  0, count_id:  0, count_total: 186366, counts_aa:   6066, counts_cg: 180300
ubq_site: k29, hdbscan_id:  8, count_id:  1, count_total:  99803, counts_aa:    513, counts_cg:  99290
ubq_site: k29, hdbscan_id:  3, count_id:  2, count_total:  48921, counts_aa:   7774, counts_cg:  41147
ubq_site: k29, hdbscan_id: 17, count_id:  3, count_total:  44759, counts_aa:    708, counts_cg:  44051
ubq_site: k29, hdbscan_id:  6, count_id:  4, count_total:  28701, counts_aa:   1326, counts_cg:  27375
ubq_site: k29, hdbscan_id: 10, count_id:  5, count_total:  22909, counts_aa:   2988, counts_cg:  19921
ubq_site: k29, hdbscan_id: 15, count_id:  6, count_total:  16151, counts_aa:   1051, counts_cg:  15100
ubq_site: k29, hdbscan_id:  5, count_id:  7, count_total:  14024, counts_aa:    313, counts_cg:  13711
ubq_site: k29, hdbscan_id: 14, count_id:  8, count_total:  12681, counts

In [33]:
for ubq_site, rows in aa_df.groupby([('data', '', 'ubq_site')]):   
    if ubq_site not in cluster_ids:
        cluster_ids[ubq_site] = np.concatenate([np.load(f'/mnt/data/kevin/xplor_analysis_files/cluster_membership_aa_{ubq_site}.npy'), np.load(f'/mnt/data/kevin/xplor_analysis_files/cluster_membership_cg_{ubq_site}.npy')])
        
    hdbscan_cluster_ids, hdbscan_cluster_counts = np.unique(cluster_ids[ubq_site], return_counts=True)
    hdbscan_cluster_count_ids = np.argsort(- hdbscan_counts) - 1
    
    aa_df_cluster_ids, aa_df_cluster_counts = np.unique(rows[('data', '', 'cluster_id')].values, return_counts=True)
    aa_df_cluster_count_ids = np.argsort(- hdbscan_counts) - 1
    print(ubq_site)
    print(hdbscan_cluster_ids)
    print(hdbscan_cluster_counts)
    print(hdbscan_cluster_count_ids)
    print(aa_df_cluster_ids)
    print(aa_df_cluster_counts)
    print(aa_df_cluster_count_ids)
    print()
    
#     if ubq_site == 'k6':
#         for i, (hdbscan_id, count_id) in enumerate(zip(hdbscan_ids, count_ids)):
            
#             hdbscan_id_from_df = rows[rows[('data', '', 'count_id')] == count_id][('data', '', 'cluster_id')].unique()[0]
#             print(hdbscan_id_from_df)
#             print(hdbscan_id)
    
#     for hdbscan_id, count_id in zip(hdbscan_ids, count_ids):
#         count_id_from_df = rows[rows[('data', '', 'cluster_id')] == hdbscan_id][('data', '', 'count_id')].unique()
#         assert len(count_id_from_df) == 1
#         count_id_from_df = count_id_from_df[0]
#         if count_id_from_df != count_id:
#             print(ubq_site)
#             print(count_id_from_df, count_id)
#             raise Exception("STOP")


#         hdbscan_id_from_df = rows[rows[('data', '', 'count_id')] == count_id][('data', '', 'cluster_id')].unique()
#         assert len(hdbscan_id_from_df) == 1
#         hdbscan_id_from_df = hdbscan_id_from_df[0]
#         if hdbscan_id_from_df != hdbscan_id:
#             print(ubq_site)
#             print(hdbscan_id_from_df, hdbscan_id)
#             raise Exception("STOP")
#     break
    
#     print(count_id, count_ids[i])
#     print(hdbscan_id, hdbscan_ids[i], '\n')
    
#     uniques, counts = np.unique(cluster_ids[ubq_site], return_counts=True)
#     argsort = np.argsort(- counts) - 1
    
    # the hdbscan_id cluster 1 is missing from the aa_df, as it has no aa structures
#     if ubq_site == 'k29':
#         argsort = argsort[uniques != 1]
#         uniques = uniques[uniques != 1]
    
    # uniques is hdbscan_id
    # argsort is count_id
    
#     idx = np.where(argsort == count_id)[0]
#     test_hdbscan_id = uniques[idx][0]
    
#     if ubq_site == 'k29':
#         print(i)

    
#     if uniques[i] != count_id:
#         print(ubq_site)
#         print(i)
#         print(uniques)
#         print(argsort)
#         print(count_id)
#         print(hdbscan_id)
#         raise Exception()
#     if argsort[i] != hdbscan_id:
#         print(ubq_site)
#         print(uniques)
#         print(argsort)
#         print(count_id)
#         print(hdbscan_id)
#         print(aa_df[aa_df[('data', '', 'ubq_site')] == 'k29'][('data', '', 'cluster_id')].unique())
#         raise Exception()

k29
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[572515 186366   6436  11039  48921   5148  14024  28701   3379  99803
   7142  22909  10095   4112   4606  12681  16151   7428  44759   4662]
[-1  5 12  9 10  6  7  0  8  1  3  4  2 11]
[-1  0  1  2  3  4  5  6  7  8  9 10 12 13 14 15 16 17 18]
[84740  6058    29  1704  7772   379   312  1323    48   511   522  2986
    55  1670   650  1051   191   708    92]
[-1  5 12  9 10  6  7  0  8  1  3  4  2 11]

k33
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23]
[675738   9010   4838   2584   3050   7593   4735   4326   5877  21385
   5140  29716   6174   6179  30973   9425  20462  21253 119908   9469
  22921  95897  29250  31411   3231]
[-1  5 12  9 10  6  7  0  8  1  3  4  2 11]
[-1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
 23]
[124562   9008   4836   2583   3048   6146     43     39    163   3797
    320    476    179    700  14406   3214   1828    937   2107    131
 

In [ ]:

if 